# Generated by Django 3.1.6 on 2021-03-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210301_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='curr_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='curr_bidder',
        ),
    ]
