# Generated by Django 3.1.7 on 2021-03-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210311_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
